### ISSUE TITLE
页面重新渲染报错

### ISSUE THREAD

**Issue by songdun** [reactive-react/xreact#20]
我在一个已经ok的页面里调用了
`ReactDOM.render(
    <Most>
      <AddAssetPage /> //这是一个新页面的组件
    </Most>, document.getElementById("root")
  );`
来重新渲染这个页面的时候出现了以下报错，如果在一开始就使用以上的代码的时候是正确不报错的，这个地方需要做什么特殊处理吗？

```
There is Error in your reducer: SyntaxError: Unexpected token C in JSON at position 0
    at Object.parse (<anonymous>)
    at com.cognitect.transducers.Map.f (entry.js?6094e2d…:18346)
    at com.cognitect.transducers.Map.@@transducer/step (dll.js:184)
    at com.cognitect.transducers.Filter.@@transducer/step (dll.js:184)
    at l.step (dll.js:134)
    at a.event (dll.js:134)
    at _eventBound (dll.js:147) SyntaxError: Unexpected token C in JSON at position 0
    at Object.parse (<anonymous>)
    at com.cognitect.transducers.Map.f (http://127.0.0.1:8777/index/index/entry.js?6094e2d1493d9fa118d9:18346:18)
    at com.cognitect.transducers.Map.@@transducer/step (http://127.0.0.1:8777/dll/dll.js:184:20607)
    at com.cognitect.transducers.Filter.@@transducer/step (http://127.0.0.1:8777/dll/dll.js:184:21242)
    at l.step (http://127.0.0.1:8777/dll/dll.js:134:1061)
    at a.event (http://127.0.0.1:8777/dll/dll.js:134:490)
    at _eventBound (http://127.0.0.1:8777/dll/dll.js:147:202)
```

**Comment by jcouyang** [comment]
看起来像是你的reducer中处理的JSON有问题，你能描述下问题吗，比如reducer里面做了什么？

**Comment by songdun** [comment]
找到了 后台返回的JSON有问题 现在遇到个问题 普通的编辑详情 我把一个表单的数据绑定到流之后让表单显示出来， 然后需要怎么来改变这个流呢？按照那个search的例子的话 我每次输入都需要发送请求去获取一遍数据，如果不按照这样的话，不管我怎么输入，它显示的值都不会变。

**Comment by jcouyang** [comment]
能在具体一些你的问题吗？不是很懂你描述的问题
如果是表单的话，react有两种表单控制，一种是value由你的state控制，另一种是不控制，只给defaultValue，建议给选后一种，如果是表单

**Comment by songdun** [comment]
用defaultValue的话 只能先写固定的数据进去 如写defaultValue=“123” ，就能在input里看到123；但是数据是从props.results里来的啊 所以我写的是 defaultValue={ props.results&& props.results.bankName}  这样的话 这个input最开始渲染的时候 props里还没有results这个属性，当从接口返回数据再挂在props的时候，input里不会显示任何值了，我用chrome的react插件来看input的value里是有值的，但是没有在页面显示，是我哪里写错了吗？

**Comment by songdun** [comment]
找到解决方法了  写成{props.results && <Input defaultValue={props.results.bankName} />} 这样才能显示，
现在这个页面是新增和编辑都用这个，我只能写成
`{
                  props.results && <Input defaultValue={props.results.bankName} />
                }
                {
                  !props.results && <Input />
                }`
你有更好的办法吗？

**Comment by jcouyang** [comment]
我还是没理解你的问题，能给个最小能重现的代码例子吗
